language: php
php:
  - '7.4'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - make install
script: make lint test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
